scrollConfig: |
  {
    "sdk_config": {
      "prover_name_prefix": "snarkify_",
      "keys_dir": "/keys",
      "db_path": "/db",
      "coordinator": {
        "base_url": "https://coordinator-api.scrollsdk",
        "retry_count": 3,
        "retry_wait_time_sec": 5,
        "connection_timeout_sec": 60
      },
      "l2geth": {
        "endpoint": "https://l2-rpc.scrollsdk"
      },
      "prover": {
        "circuit_type": 2,
        "circuit_version": "v0.13.1",
        "supported_proof_types": [
            1
        ],
        "n_workers": 1
      }
    },
    "base_url": "https://api.snarkify.io",
    "api_key": "<API_KEY>",
    "service_id": "<SERVICE_ID>"
  }
