---
apiVersion: v2
description: A proving agent for Scroll SDK to generate proofs in Snarkify platform.
name: snarkify-scroll-proving-agent
version: 0.0.1
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: snarkify
    email: hello@snarkify.io
dependencies:
  - name: common
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 1.5.1
type: application
